### ISSUE TITLE
Existing Public Key

### ISSUE THREAD

**Issue by Netvisio** [averyhiebert/smart-health-cards#3]
Your code is amazing, very well designed. I was just wondering how can you encripted with an already set piblic key with out the need of generating a new one? This is the pubic key im trying to encripted with:

{"keys":[{"kty":"EC","kid":"Nlgwb6GUrU_f0agdYKc77sXM9U8en1gBu94plufPUj8","use":"sig","alg":"ES256","crv":"P-256","x":"ibapbMkHMlkR3D-AU0VTFDsiidQ49oD9Ha7VY8Gao3s","y":"arXU5frZGOvTZpvg045rHC7y0fqVOS3dKqJbUYhW5gw"}]}

_Originally posted by @Netvisio in https://github.com/averyhiebert/smart-health-cards/issues/1#issuecomment-997425529_

**Comment by averyhiebert** [comment]
If I knew how to break elliptic curve cryptography I would have the option to commit crimes much more lucrative than simply helping you impersonate Ontario Health.
